id: P008073
initial_creation_type: ocr
source_metadata:
  id: bdr:W29520
  title: བྱ་ནག་སྤུན་གསུམ།
  author: ''
  volumes:
    d14ddb2d838f41c1bba2e4f04937c659:
      image_group_id: I1KG22703
      title: ''
      volume_number: 1
      total_pages: 240
ebook_metadata:
  title: བྱ་ནག་སྤུན་གསུམ།
  author: ''
  sku: P008073
  cover: cover.jpg
  layers:
  - pagination
