id: P008073
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 12:59:38.322620
source_metadata:
  id: bdr:W29520
  title: བྱ་ནག་སྤུན་གསུམ།
  author: ''
  volumes:
    81c26c7a2f7041138bbe13715fdf6623:
      image_group_id: I1KG22703
      title: Volume 1 of bya nag spun gsum
      volume_number: 1
      total_pages: 240
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
