id: I2DFD76D7
legacy_id: P008073
ocr_import_info:
  bdrc_scan_id: W29520
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T10:22:57'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T13:52:39.872699+00:00'
last_modified: 2022-09-02 21:53:15.188331
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W29520
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW29520
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བྱ་ནག་སྤུན་གསུམ།
  author: གཅོད་པ་དོན་གྲུབ།
statistics:
  ocr_word_mean_confidence_index: 0.8848723773440923
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I1KG22703:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG22703
      total_pages: 240
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG22703.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.8848723773440923
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
